// 📂 File: lib/core/localization/app_localizations.dart

import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';

import '../../services/database_service.dart';

class AppLanguageProvider extends ChangeNotifier {
  AppLanguageProvider() {
    _loadSavedLanguage();
  }

  static const String _languageKey = 'app_language';
  final Box<dynamic> _settingsBox = Hive.box(DatabaseService.settingsBoxName);

  String _currentLanguage = 'en';

  String get currentLanguage => _currentLanguage;

  Future<void> changeLanguage(String languageCode) async {
    _currentLanguage = languageCode;
    await _settingsBox.put(_languageKey, languageCode);
    notifyListeners();
  }

  String translate(String key) {
    return _localizedValues[_currentLanguage]?[key] ?? _localizedValues['en']?[key] ?? key;
  }

  String translateWithArgs(String key, [Map<String, String> args = const {}]) {
    var value = translate(key);
    for (final entry in args.entries) {
      value = value.replaceAll('{${entry.key}}', entry.value);
    }
    return value;
  }

  void _loadSavedLanguage() {
    final saved = _settingsBox.get(_languageKey) as String?;
    if (saved != null && _localizedValues.containsKey(saved)) {
      _currentLanguage = saved;
    }
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Spiritual Tracker',
      'tab_dashboard': 'Dashboard',
      'tab_prayer': 'Prayer',
      'tab_dhikr': 'Dhikr',
      'tab_notes': 'Notes',
      'tab_settings': 'Settings',
      'common_cancel': 'Cancel',
      'common_save': 'Save',
      'common_add': 'Add',
      'common_delete': 'Delete',
      'common_close': 'Close',
      'common_update': 'Update',
      'common_rename': 'Rename',
      'common_move': 'Move',
      'common_open': 'Open',
      'common_share': 'Share',
      'common_name': 'Name',
      'common_title': 'Title',
      'common_text': 'Text',
      'dashboard_summary_title': 'Your Spiritual Summary',
      'dashboard_pending_qadha': 'Pending Qadha',
      'dashboard_today_dhikr': 'Today\'s Dhikr',
      'dashboard_week_dhikr': '7-Day Dhikr',
      'dashboard_total_dhikr': 'All-Time Dhikr',
      'dashboard_activity_title': 'Last 7 Days Activity',
      'dashboard_activity_subtitle': 'Teal shows daily dhikr counts. Orange shows pending qadha snapshot for that day.',
      'prayer_tracker_title': 'Missed Prayer Tracker',
      'prayer_tracker_subtitle': 'Only keep track of missed prayers that still need to be made up. Use + and - to update each prayer quickly.',
      'prayer_total_pending': 'Total Pending Qadha',
      'prayer_minus': 'Minus',
      'prayer_plus': 'Plus',
      'prayer_fajr': 'Fajr',
      'prayer_dhuhr': 'Dhuhr',
      'prayer_asr': 'Asr',
      'prayer_maghrib': 'Maghrib',
      'prayer_isha': 'Isha',
      'dhikr_select': 'Select Dhikr',
      'dhikr_empty': 'No dhikr added yet. Tap + to add.',
      'dhikr_tap': 'Tap anywhere to count',
      'dhikr_edit': 'Edit Dhikr',
      'dhikr_add_new': 'Add New Dhikr',
      'dhikr_hint': 'Enter Dhikr text',
      'notes_folder_button': 'Folder',
      'notes_search_hint': 'Search in this folder',
      'notes_filter_all': 'All',
      'notes_filter_image': 'Image',
      'notes_filter_pdf': 'PDF',
      'notes_filter_text': 'Text',
      'notes_current_folder': 'Folder: {name}',
      'notes_type_text': 'TEXT',
      'notes_menu_open': 'Open',
      'notes_menu_rename': 'Rename',
      'notes_menu_move': 'Move',
      'notes_menu_edit_text': 'Edit Text',
      'notes_menu_share': 'Share',
      'notes_file_missing': 'The selected file could not be found.',
      'notes_file_unavailable': 'The selected file is no longer available on this device.',
      'notes_share_failed': 'Unable to share this item right now.',
      'notes_add_text': 'Add Text Note',
      'notes_upload_image': 'Upload Image',
      'notes_upload_pdf': 'Upload PDF',
      'notes_import_image_failed': 'Unable to import the selected image.',
      'notes_import_pdf_failed': 'Unable to import the selected PDF.',
      'notes_file_name': 'File Name',
      'notes_save_failed': 'Unable to save this file.',
      'notes_added_success': '{type} added successfully.',
      'notes_rename_folder': 'Rename Folder',
      'notes_delete_folder': 'Delete Folder',
      'notes_create_folder': 'Create Folder',
      'notes_folder_name': 'Folder name',
      'notes_folder_empty_error': 'Folder name cannot be empty.',
      'notes_folder_exists_error': 'A folder with this name already exists.',
      'notes_delete_folder_title': 'Delete {name}?',
      'notes_delete_folder_message': 'Notes in this folder will be moved before the folder is deleted.',
      'notes_move_notes_to': 'Move notes to',
      'notes_folder_deleted': 'Folder deleted. Notes were moved safely.',
      'notes_move_item_title': 'Move item',
      'notes_choose_folder': 'Choose folder',
      'notes_create_folder_before_move': 'Create another folder before moving this item.',
      'notes_item_moved': 'Item moved successfully.',
      'notes_delete_item_title': 'Delete item?',
      'notes_delete_item_message': 'This will permanently remove "{title}".',
      'notes_item_deleted': 'Item deleted.',
      'notes_edit_text_title': 'Edit Text Note',
      'notes_add_text_title': 'Add Text Note',
      'notes_title_and_text_required': 'Title and text are required.',
      'notes_text_added': 'Text note added.',
      'notes_text_updated': 'Text note updated.',
      'notes_empty_search': 'No matching items were found in {folder}.',
      'notes_empty_image': 'No images in {folder} yet.',
      'notes_empty_pdf': 'No PDFs in {folder} yet.',
      'notes_empty_text': 'No text notes in {folder} yet.',
      'notes_empty_all': 'No items in {folder} yet.',
      'note_edit_add': 'Add Note',
      'note_edit_hint_title': 'Title',
      'note_edit_hint_body': 'Type your thoughts here...',
      'settings_dark_mode': 'Dark Mode',
      'settings_language': 'Language',
      'settings_backup_title': 'Phone Storage + Google Drive Backup',
      'settings_backup_subtitle': 'All data stays on the phone by default. Sign in only when you want to create a Google Drive backup or restore your old data.',
      'settings_sign_in_drive': 'Sign in to Google Drive',
      'settings_google_account': 'Google Account',
      'settings_sign_out': 'Sign out',
      'settings_last_backup': 'Last backup: {value}',
      'settings_last_backup_file': 'Last backup file: {value}',
      'settings_last_restore': 'Last restore: {value}',
      'settings_backup_to_drive': 'Backup to Drive',
      'settings_refresh_backups': 'Refresh backups',
      'settings_pause': 'Pause',
      'settings_resume': 'Resume',
      'settings_available_backups': 'Available backups',
      'settings_no_backups': 'No backup files are ready on Google Drive yet.',
      'settings_unknown_date': 'Unknown date',
      'settings_restore': 'Restore',
      'backup_status_local_only': 'Local-only mode active',
      'backup_status_signin_cancelled': 'Google sign-in cancelled',
      'backup_status_connected': 'Connected to {email}',
      'backup_status_signed_out': 'Signed out from Google Drive',
      'backup_status_preparing': 'Preparing backup archive...',
      'backup_status_signing_in': 'Signing in to Google Drive...',
      'backup_status_uploading': 'Uploading backup to Google Drive...',
      'backup_status_backup_cancelled': 'Backup cancelled',
      'backup_status_backup_completed': 'Backup completed successfully',
      'backup_status_backup_failed': 'Backup failed: {error}',
      'backup_status_loading_backups': 'Loading backups from Google Drive...',
      'backup_status_no_backups': 'No Drive backups found yet',
      'backup_status_found_backups': 'Found {count} backup file(s)',
      'backup_status_load_failed': 'Could not load backup list: {error}',
      'backup_status_downloading': 'Downloading {name}...',
      'backup_status_restore_cancelled': 'Restore cancelled',
      'backup_status_applying': 'Applying backup to local storage...',
      'backup_status_restore_completed': 'Restore completed successfully',
      'backup_status_restore_failed': 'Restore failed: {error}',
      'backup_status_upload_progress': 'Uploading {current} MB of {total} MB',
      'backup_status_download_progress': 'Downloading {current} MB of {total} MB',
      'backup_status_paused': 'Backup paused',
      'backup_status_resuming': 'Resuming backup upload...',
      'backup_status_cancelling_restore': 'Cancelling restore...',
      'backup_status_cancelling_backup': 'Cancelling backup...',
    },
    'ml': {
      'app_title': 'സ്പിരിച്വൽ ട്രാക്കർ',
      'tab_dashboard': 'ഡാഷ്‌ബോർഡ്',
      'tab_prayer': 'നിസ്കാരം',
      'tab_dhikr': 'ദിക്റ്',
      'tab_notes': 'നോട്ട്സ്',
      'tab_settings': 'സെറ്റിംഗ്സ്',
      'common_cancel': 'റദ്ദാക്കുക',
      'common_save': 'സേവ്',
      'common_add': 'ചേർക്കുക',
      'common_delete': 'ഡിലീറ്റ്',
      'common_close': 'അടയ്ക്കുക',
      'common_update': 'അപ്ഡേറ്റ്',
      'common_rename': 'പേര് മാറ്റുക',
      'common_move': 'മാറ്റുക',
      'common_open': 'തുറക്കുക',
      'common_share': 'ഷെയർ',
      'common_name': 'പേര്',
      'common_title': 'തലക്കെട്ട്',
      'common_text': 'ടെക്സ്റ്റ്',
      'dashboard_summary_title': 'നിങ്ങളുടെ ആത്മീയ ചുരുക്കം',
      'dashboard_pending_qadha': 'വീട്ടാനുള്ള ഖളാഅ്',
      'dashboard_today_dhikr': 'ഇന്നത്തെ ദിക്റ്',
      'dashboard_week_dhikr': '7 ദിവസത്തെ ദിക്റ്',
      'dashboard_total_dhikr': 'ആകെ ദിക്റ്',
      'dashboard_activity_title': 'കഴിഞ്ഞ 7 ദിവസത്തെ പ്രവർത്തനം',
      'dashboard_activity_subtitle': 'തവിട്ട് പച്ച ബാർ ദിവസേന ദിക്റ് എണ്ണവും ഓറഞ്ച് ബാർ ആ ദിവസത്തെ ഖളാഅ് നിലയും കാണിക്കുന്നു.',
      'prayer_tracker_title': 'മിസ്സ് ചെയ്ത നിസ്കാര ട്രാക്കർ',
      'prayer_tracker_subtitle': 'വീട്ടാനുള്ള നിസ്കാരങ്ങൾ മാത്രം ട്രാക്ക് ചെയ്യുക. ഓരോ നിസ്കാരത്തിനും +, - ഉപയോഗിച്ച് പെട്ടെന്ന് അപ്ഡേറ്റ് ചെയ്യാം.',
      'prayer_total_pending': 'ആകെ വീട്ടാനുള്ള ഖളാഅ്',
      'prayer_minus': 'കുറയ്ക്കുക',
      'prayer_plus': 'കൂട്ടുക',
      'prayer_fajr': 'ഫജ്റ്',
      'prayer_dhuhr': 'ദുഹ്റ്',
      'prayer_asr': 'അസർ',
      'prayer_maghrib': 'മഗ്രിബ്',
      'prayer_isha': 'ഇഷാ',
      'dhikr_select': 'ദിക്റ് തിരഞ്ഞെടുക്കുക',
      'dhikr_empty': 'ഇതുവരെ ദിക്റ് ചേർത്തിട്ടില്ല. + അമർത്തി ചേർക്കുക.',
      'dhikr_tap': 'എവിടെയും തൊട്ട് എണ്ണം കൂട്ടാം',
      'dhikr_edit': 'ദിക്റ് എഡിറ്റ് ചെയ്യുക',
      'dhikr_add_new': 'പുതിയ ദിക്റ് ചേർക്കുക',
      'dhikr_hint': 'ദിക്റ് ടെക്സ്റ്റ് നൽകുക',
      'notes_folder_button': 'ഫോൾഡർ',
      'notes_search_hint': 'ഈ ഫോൾഡറിൽ തിരയുക',
      'notes_filter_all': 'എല്ലാം',
      'notes_filter_image': 'ഇമേജ്',
      'notes_filter_pdf': 'PDF',
      'notes_filter_text': 'ടെക്സ്റ്റ്',
      'notes_current_folder': 'ഫോൾഡർ: {name}',
      'notes_type_text': 'ടെക്സ്റ്റ്',
      'notes_menu_open': 'തുറക്കുക',
      'notes_menu_rename': 'പേര് മാറ്റുക',
      'notes_menu_move': 'മാറ്റുക',
      'notes_menu_edit_text': 'ടെക്സ്റ്റ് എഡിറ്റ്',
      'notes_menu_share': 'ഷെയർ',
      'notes_file_missing': 'തിരഞ്ഞെടുത്ത ഫയൽ കണ്ടെത്താനായില്ല.',
      'notes_file_unavailable': 'തിരഞ്ഞെടുത്ത ഫയൽ ഈ ഉപകരണത്തിൽ ഇനി ലഭ്യമല്ല.',
      'notes_share_failed': 'ഇപ്പോൾ ഈ ഐറ്റം ഷെയർ ചെയ്യാൻ കഴിഞ്ഞില്ല.',
      'notes_add_text': 'ടെക്സ്റ്റ് നോട് ചേർക്കുക',
      'notes_upload_image': 'ഇമേജ് അപ്‌ലോഡ്',
      'notes_upload_pdf': 'PDF അപ്‌ലോഡ്',
      'notes_import_image_failed': 'തിരഞ്ഞെടുത്ത ഇമേജ് ഇമ്പോർട്ട് ചെയ്യാനായില്ല.',
      'notes_import_pdf_failed': 'തിരഞ്ഞെടുത്ത PDF ഇമ്പോർട്ട് ചെയ്യാനായില്ല.',
      'notes_file_name': 'ഫയൽ പേര്',
      'notes_save_failed': 'ഈ ഫയൽ സേവ് ചെയ്യാനായില്ല.',
      'notes_added_success': '{type} വിജയകരമായി ചേർത്തു.',
      'notes_rename_folder': 'ഫോൾഡർ പേര് മാറ്റുക',
      'notes_delete_folder': 'ഫോൾഡർ ഡിലീറ്റ് ചെയ്യുക',
      'notes_create_folder': 'ഫോൾഡർ സൃഷ്ടിക്കുക',
      'notes_folder_name': 'ഫോൾഡർ പേര്',
      'notes_folder_empty_error': 'ഫോൾഡർ പേര് ഒഴിഞ്ഞിരിക്കരുത്.',
      'notes_folder_exists_error': 'ഈ പേരിൽ ഒരു ഫോൾഡർ നിലവിലുണ്ട്.',
      'notes_delete_folder_title': '{name} ഡിലീറ്റ് ചെയ്യണോ?',
      'notes_delete_folder_message': 'ഫോൾഡർ ഡിലീറ്റ് ചെയ്യുന്നതിന് മുമ്പ് ഇതിലെ നോട്ടുകൾ മറ്റൊരു ഫോൾഡറിലേക്ക് മാറ്റും.',
      'notes_move_notes_to': 'നോട്ടുകൾ ഇവിടെക്ക് മാറ്റുക',
      'notes_folder_deleted': 'ഫോൾഡർ ഡിലീറ്റ് ചെയ്തു. നോട്ടുകൾ സുരക്ഷിതമായി മാറ്റി.',
      'notes_move_item_title': 'ഐറ്റം മാറ്റുക',
      'notes_choose_folder': 'ഫോൾഡർ തിരഞ്ഞെടുക്കുക',
      'notes_create_folder_before_move': 'ഈ ഐറ്റം മാറ്റാൻ ആദ്യം മറ്റൊരു ഫോൾഡർ സൃഷ്ടിക്കുക.',
      'notes_item_moved': 'ഐറ്റം വിജയകരമായി മാറ്റി.',
      'notes_delete_item_title': 'ഐറ്റം ഡിലീറ്റ് ചെയ്യണോ?',
      'notes_delete_item_message': '"{title}" സ്ഥിരമായി ഡിലീറ്റ് ചെയ്യും.',
      'notes_item_deleted': 'ഐറ്റം ഡിലീറ്റ് ചെയ്തു.',
      'notes_edit_text_title': 'ടെക്സ്റ്റ് നോട് എഡിറ്റ് ചെയ്യുക',
      'notes_add_text_title': 'ടെക്സ്റ്റ് നോട് ചേർക്കുക',
      'notes_title_and_text_required': 'തലക്കെട്ടും ടെക്സ്റ്റും നിർബന്ധമാണ്.',
      'notes_text_added': 'ടെക്സ്റ്റ് നോട് ചേർത്തു.',
      'notes_text_updated': 'ടെക്സ്റ്റ് നോട് അപ്ഡേറ്റ് ചെയ്തു.',
      'notes_empty_search': '{folder} ഫോൾഡറിൽ പൊരുത്തപ്പെടുന്ന ഐറ്റങ്ങൾ കണ്ടെത്തിയില്ല.',
      'notes_empty_image': '{folder} ഫോൾഡറിൽ ഇമേജുകളില്ല.',
      'notes_empty_pdf': '{folder} ഫോൾഡറിൽ PDF-കൾ ഇല്ല.',
      'notes_empty_text': '{folder} ഫോൾഡറിൽ ടെക്സ്റ്റ് നോട്ടുകൾ ഇല്ല.',
      'notes_empty_all': '{folder} ഫോൾഡറിൽ ഐറ്റങ്ങൾ ഒന്നുമില്ല.',
      'note_edit_add': 'നോട് ചേർക്കുക',
      'note_edit_hint_title': 'തലക്കെട്ട്',
      'note_edit_hint_body': 'നിങ്ങളുടെ ചിന്തകൾ ഇവിടെ എഴുതൂ...',
      'settings_dark_mode': 'ഡാർക്ക് മോഡ്',
      'settings_language': 'ഭാഷ',
      'settings_backup_title': 'ഫോൺ സ്റ്റോറേജ് + ഗൂഗിൾ ഡ്രൈവ് ബാക്കപ്പ്',
      'settings_backup_subtitle': 'ഡാറ്റ ഡീഫോൾട്ടായി ഫോണിൽ തന്നെ നിലനിൽക്കും. ബാക്കപ്പ് എടുക്കാനോ പഴയ ഡാറ്റ തിരിച്ചുകൊണ്ടുവരാനോ വേണമെങ്കിൽ മാത്രം ഗൂഗിൾ ഡ്രൈവിൽ സൈൻ ഇൻ ചെയ്യൂ.',
      'settings_sign_in_drive': 'ഗൂഗിൾ ഡ്രൈവിൽ സൈൻ ഇൻ ചെയ്യുക',
      'settings_google_account': 'ഗൂഗിൾ അക്കൗണ്ട്',
      'settings_sign_out': 'സൈൻ ഔട്ട്',
      'settings_last_backup': 'അവസാന ബാക്കപ്പ്: {value}',
      'settings_last_backup_file': 'അവസാന ബാക്കപ്പ് ഫയൽ: {value}',
      'settings_last_restore': 'അവസാന റിസ്റ്റോർ: {value}',
      'settings_backup_to_drive': 'ഡ്രൈവിലേക്ക് ബാക്കപ്പ്',
      'settings_refresh_backups': 'ബാക്കപ്പുകൾ റിഫ്രഷ് ചെയ്യുക',
      'settings_pause': 'താൽക്കാലികമായി നിർത്തുക',
      'settings_resume': 'തുടരുക',
      'settings_available_backups': 'ലഭ്യമായ ബാക്കപ്പുകൾ',
      'settings_no_backups': 'ഗൂഗിൾ ഡ്രൈവിൽ ഇതുവരെ ബാക്കപ്പ് ഫയലുകളില്ല.',
      'settings_unknown_date': 'തീയതി അറിയില്ല',
      'settings_restore': 'റിസ്റ്റോർ',
      'backup_status_local_only': 'ലോകൽ മോഡ് സജീവമാണ്',
      'backup_status_signin_cancelled': 'ഗൂഗിൾ സൈൻ ഇൻ റദ്ദാക്കി',
      'backup_status_connected': '{email} ആയി കണക്റ്റ് ചെയ്തു',
      'backup_status_signed_out': 'ഗൂഗിൾ ഡ്രൈവിൽ നിന്ന് സൈൻ ഔട്ട് ചെയ്തു',
      'backup_status_preparing': 'ബാക്കപ്പ് ആർകൈവ് തയ്യാറാക്കുന്നു...',
      'backup_status_signing_in': 'ഗൂഗിൾ ഡ്രൈവിലേക്ക് സൈൻ ഇൻ ചെയ്യുന്നു...',
      'backup_status_uploading': 'ഗൂഗിൾ ഡ്രൈവിലേക്ക് ബാക്കപ്പ് അപ്‌ലോഡ് ചെയ്യുന്നു...',
      'backup_status_backup_cancelled': 'ബാക്കപ്പ് റദ്ദാക്കി',
      'backup_status_backup_completed': 'ബാക്കപ്പ് വിജയകരമായി പൂർത്തിയായി',
      'backup_status_backup_failed': 'ബാക്കപ്പ് പരാജയപ്പെട്ടു: {error}',
      'backup_status_loading_backups': 'ഗൂഗിൾ ഡ്രൈവിൽ നിന്ന് ബാക്കപ്പുകൾ ലോഡ് ചെയ്യുന്നു...',
      'backup_status_no_backups': 'ഡ്രൈവിൽ ബാക്കപ്പ് ഒന്നും കണ്ടെത്തിയില്ല',
      'backup_status_found_backups': '{count} ബാക്കപ്പ് ഫയൽ കണ്ടെത്തി',
      'backup_status_load_failed': 'ബാക്കപ്പ് പട്ടിക ലോഡ് ചെയ്യാനായില്ല: {error}',
      'backup_status_downloading': '{name} ഡൗൺലോഡ് ചെയ്യുന്നു...',
      'backup_status_restore_cancelled': 'റിസ്റ്റോർ റദ്ദാക്കി',
      'backup_status_applying': 'ലോകൽ സ്റ്റോറേജിലേക്ക് ബാക്കപ്പ് പ്രയോഗിക്കുന്നു...',
      'backup_status_restore_completed': 'റിസ്റ്റോർ വിജയകരമായി പൂർത്തിയായി',
      'backup_status_restore_failed': 'റിസ്റ്റോർ പരാജയപ്പെട്ടു: {error}',
      'backup_status_upload_progress': '{current} MB / {total} MB അപ്‌ലോഡ് ചെയ്യുന്നു',
      'backup_status_download_progress': '{current} MB / {total} MB ഡൗൺലോഡ് ചെയ്യുന്നു',
      'backup_status_paused': 'ബാക്കപ്പ് താൽക്കാലികമായി നിർത്തി',
      'backup_status_resuming': 'ബാക്കപ്പ് അപ്‌ലോഡ് വീണ്ടും തുടരുന്നു...',
      'backup_status_cancelling_restore': 'റിസ്റ്റോർ റദ്ദാക്കുന്നു...',
      'backup_status_cancelling_backup': 'ബാക്കപ്പ് റദ്ദാക്കുന്നു...',
    },
    'ar': {
      'app_title': 'المتعقب الروحي',
      'tab_dashboard': 'لوحة القيادة',
      'tab_prayer': 'الصلاة',
      'tab_dhikr': 'الذكر',
      'tab_notes': 'الملاحظات',
      'tab_settings': 'الإعدادات',
      'common_cancel': 'إلغاء',
      'common_save': 'حفظ',
      'common_add': 'إضافة',
      'common_delete': 'حذف',
      'common_close': 'إغلاق',
      'common_update': 'تحديث',
      'common_rename': 'إعادة تسمية',
      'common_move': 'نقل',
      'common_open': 'فتح',
      'common_share': 'مشاركة',
      'common_name': 'الاسم',
      'common_title': 'العنوان',
      'common_text': 'النص',
      'dashboard_summary_title': 'ملخصك الروحي',
      'dashboard_pending_qadha': 'الصلوات الفائتة المتبقية',
      'dashboard_today_dhikr': 'ذكر اليوم',
      'dashboard_week_dhikr': 'ذكر 7 أيام',
      'dashboard_total_dhikr': 'إجمالي الذكر',
      'dashboard_activity_title': 'نشاط آخر 7 أيام',
      'dashboard_activity_subtitle': 'اللون الأخضر المائل للأزرق يوضح عدد الأذكار اليومية، والبرتقالي يوضح رصيد القضاء لذلك اليوم.',
      'prayer_tracker_title': 'متتبع الصلوات الفائتة',
      'prayer_tracker_subtitle': 'تتبّع فقط الصلوات الفائتة التي ما زالت تحتاج إلى قضاء. استخدم + و - للتحديث السريع.',
      'prayer_total_pending': 'إجمالي القضاء المتبقي',
      'prayer_minus': 'ناقص',
      'prayer_plus': 'زائد',
      'prayer_fajr': 'الفجر',
      'prayer_dhuhr': 'الظهر',
      'prayer_asr': 'العصر',
      'prayer_maghrib': 'المغرب',
      'prayer_isha': 'العشاء',
      'dhikr_select': 'اختر الذكر',
      'dhikr_empty': 'لم تتم إضافة أي ذكر بعد. اضغط + للإضافة.',
      'dhikr_tap': 'اضغط في أي مكان للعد',
      'dhikr_edit': 'تعديل الذكر',
      'dhikr_add_new': 'إضافة ذكر جديد',
      'dhikr_hint': 'أدخل نص الذكر',
      'notes_folder_button': 'مجلد',
      'notes_search_hint': 'ابحث داخل هذا المجلد',
      'notes_filter_all': 'الكل',
      'notes_filter_image': 'صورة',
      'notes_filter_pdf': 'PDF',
      'notes_filter_text': 'نص',
      'notes_current_folder': 'المجلد: {name}',
      'notes_type_text': 'نص',
      'notes_menu_open': 'فتح',
      'notes_menu_rename': 'إعادة تسمية',
      'notes_menu_move': 'نقل',
      'notes_menu_edit_text': 'تعديل النص',
      'notes_menu_share': 'مشاركة',
      'notes_file_missing': 'تعذر العثور على الملف المحدد.',
      'notes_file_unavailable': 'الملف المحدد لم يعد متاحًا على هذا الجهاز.',
      'notes_share_failed': 'تعذر مشاركة هذا العنصر الآن.',
      'notes_add_text': 'إضافة ملاحظة نصية',
      'notes_upload_image': 'رفع صورة',
      'notes_upload_pdf': 'رفع PDF',
      'notes_import_image_failed': 'تعذر استيراد الصورة المحددة.',
      'notes_import_pdf_failed': 'تعذر استيراد ملف PDF المحدد.',
      'notes_file_name': 'اسم الملف',
      'notes_save_failed': 'تعذر حفظ هذا الملف.',
      'notes_added_success': 'تمت إضافة {type} بنجاح.',
      'notes_rename_folder': 'إعادة تسمية المجلد',
      'notes_delete_folder': 'حذف المجلد',
      'notes_create_folder': 'إنشاء مجلد',
      'notes_folder_name': 'اسم المجلد',
      'notes_folder_empty_error': 'لا يمكن أن يكون اسم المجلد فارغًا.',
      'notes_folder_exists_error': 'يوجد مجلد بهذا الاسم بالفعل.',
      'notes_delete_folder_title': 'حذف {name}؟',
      'notes_delete_folder_message': 'سيتم نقل الملاحظات من هذا المجلد قبل حذفه.',
      'notes_move_notes_to': 'انقل الملاحظات إلى',
      'notes_folder_deleted': 'تم حذف المجلد ونقل الملاحظات بأمان.',
      'notes_move_item_title': 'نقل العنصر',
      'notes_choose_folder': 'اختر المجلد',
      'notes_create_folder_before_move': 'أنشئ مجلدًا آخر قبل نقل هذا العنصر.',
      'notes_item_moved': 'تم نقل العنصر بنجاح.',
      'notes_delete_item_title': 'حذف العنصر؟',
      'notes_delete_item_message': 'سيتم حذف "{title}" نهائيًا.',
      'notes_item_deleted': 'تم حذف العنصر.',
      'notes_edit_text_title': 'تعديل الملاحظة النصية',
      'notes_add_text_title': 'إضافة ملاحظة نصية',
      'notes_title_and_text_required': 'العنوان والنص مطلوبان.',
      'notes_text_added': 'تمت إضافة الملاحظة النصية.',
      'notes_text_updated': 'تم تحديث الملاحظة النصية.',
      'notes_empty_search': 'لم يتم العثور على عناصر مطابقة داخل {folder}.',
      'notes_empty_image': 'لا توجد صور داخل {folder} بعد.',
      'notes_empty_pdf': 'لا توجد ملفات PDF داخل {folder} بعد.',
      'notes_empty_text': 'لا توجد ملاحظات نصية داخل {folder} بعد.',
      'notes_empty_all': 'لا توجد عناصر داخل {folder} بعد.',
      'note_edit_add': 'إضافة ملاحظة',
      'note_edit_hint_title': 'العنوان',
      'note_edit_hint_body': 'اكتب أفكارك هنا...',
      'settings_dark_mode': 'الوضع الداكن',
      'settings_language': 'اللغة',
      'settings_backup_title': 'تخزين الهاتف + نسخ احتياطي في Google Drive',
      'settings_backup_subtitle': 'تبقى جميع البيانات على الهاتف افتراضيًا. سجّل الدخول فقط عندما تريد إنشاء نسخة احتياطية أو استعادة بياناتك القديمة.',
      'settings_sign_in_drive': 'تسجيل الدخول إلى Google Drive',
      'settings_google_account': 'حساب Google',
      'settings_sign_out': 'تسجيل الخروج',
      'settings_last_backup': 'آخر نسخة احتياطية: {value}',
      'settings_last_backup_file': 'آخر ملف نسخة احتياطية: {value}',
      'settings_last_restore': 'آخر استعادة: {value}',
      'settings_backup_to_drive': 'نسخ احتياطي إلى Drive',
      'settings_refresh_backups': 'تحديث النسخ الاحتياطية',
      'settings_pause': 'إيقاف مؤقت',
      'settings_resume': 'استئناف',
      'settings_available_backups': 'النسخ الاحتياطية المتاحة',
      'settings_no_backups': 'لا توجد ملفات نسخ احتياطي جاهزة على Google Drive بعد.',
      'settings_unknown_date': 'تاريخ غير معروف',
      'settings_restore': 'استعادة',
      'backup_status_local_only': 'وضع التخزين المحلي مفعل',
      'backup_status_signin_cancelled': 'تم إلغاء تسجيل الدخول إلى Google',
      'backup_status_connected': 'تم الاتصال بالحساب {email}',
      'backup_status_signed_out': 'تم تسجيل الخروج من Google Drive',
      'backup_status_preparing': 'جارٍ تجهيز ملف النسخة الاحتياطية...',
      'backup_status_signing_in': 'جارٍ تسجيل الدخول إلى Google Drive...',
      'backup_status_uploading': 'جارٍ رفع النسخة الاحتياطية إلى Google Drive...',
      'backup_status_backup_cancelled': 'تم إلغاء النسخة الاحتياطية',
      'backup_status_backup_completed': 'اكتملت النسخة الاحتياطية بنجاح',
      'backup_status_backup_failed': 'فشل النسخ الاحتياطي: {error}',
      'backup_status_loading_backups': 'جارٍ تحميل النسخ الاحتياطية من Google Drive...',
      'backup_status_no_backups': 'لم يتم العثور على نسخ احتياطية على Drive',
      'backup_status_found_backups': 'تم العثور على {count} ملف نسخ احتياطي',
      'backup_status_load_failed': 'تعذر تحميل قائمة النسخ الاحتياطية: {error}',
      'backup_status_downloading': 'جارٍ تنزيل {name}...',
      'backup_status_restore_cancelled': 'تم إلغاء الاستعادة',
      'backup_status_applying': 'جارٍ تطبيق النسخة الاحتياطية على التخزين المحلي...',
      'backup_status_restore_completed': 'اكتملت الاستعادة بنجاح',
      'backup_status_restore_failed': 'فشلت الاستعادة: {error}',
      'backup_status_upload_progress': 'جارٍ رفع {current} من {total} ميغابايت',
      'backup_status_download_progress': 'جارٍ تنزيل {current} من {total} ميغابايت',
      'backup_status_paused': 'تم إيقاف النسخ الاحتياطي مؤقتًا',
      'backup_status_resuming': 'جارٍ استئناف رفع النسخة الاحتياطية...',
      'backup_status_cancelling_restore': 'جارٍ إلغاء الاستعادة...',
      'backup_status_cancelling_backup': 'جارٍ إلغاء النسخ الاحتياطي...',
    },
  };
}
