# 📂 File: .github/workflows/build.yml

name: Build Flutter App
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v3 മാറ്റി v4 ആക്കി
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install Dependencies
        run: flutter pub get
        
      - name: Generate App Icons
        run: dart run flutter_launcher_icons

      - name: Build APK
        run: flutter build apk --release
        
      - name: Upload APK
        uses: actions/upload-artifact@v4 # v3 മാറ്റി v4 ആക്കി
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk